// Auto-generated by deploy script - DO NOT EDIT MANUALLY
export const networks = {
  "sepolia": {
    "chainId": 11155111,
    "name": "Sepolia",
    "rpcUrl": "https://sepolia.infura.io/v3/",
    "factory": "0xE93324086a82c5CC0B132Ea3173b4Af70633B2b6",
    "router": "0xd6E93fc3ba53615017F92f9138FF92c0967de869",
    "weth": "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14"
  }
};

export const getNetworkConfig = (chainId) => {
  return Object.values(networks).find(n => n.chainId === chainId);
};
